'use strict';
const $=s=>document.querySelector(s), base=window.SKYLANDERS_DATA;
const KEY='skylanders-local-draft-v1';
let edits={},view='missing',editing=false,limit=40,activeId=null;
try{edits=validate(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{edits={};}
function validate(data){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('Ogiltig backup');const out={};for(const [id,v] of Object.entries(data)){if(!base.items.some(i=>i.id===id))continue;if(!v||!['owned','missing'].includes(v.status)||!(v.quantity===null||Number.isInteger(v.quantity)&&v.quantity>=0&&v.quantity<=9999)||typeof v.notes!=='string'||v.notes.length>4000||v.status==='missing'&&v.quantity!==0||v.status==='owned'&&v.quantity===0)throw Error('Ogiltiga samlingsuppgifter');out[id]={status:v.status,quantity:v.quantity,notes:v.notes};}return out;}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function all(){return base.items.map(i=>({...i,...edits[i.id]}));}
function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').hidden=true,4000);}
for(const field of ['game','element','type']){const values=[...new Set([...base.items,...base.review].map(i=>i[field]))].sort((a,b)=>a.localeCompare(b,'sv'));for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=value;$('#'+field).append(option);}}
function render(){const items=all(),owned=items.filter(i=>i.status==='owned').length,missing=items.filter(i=>i.status==='missing').length;$('#ownedCount').textContent=owned;$('#ownedTabCount').textContent=owned;$('#missingCount').textContent=missing;$('#reviewCount').textContent=base.review.length;const titles={missing:'Vilka saknas?',owned:'Det här har vi.',all:'Hela samlingen.',review:'En variant i taget.'};$('h1').textContent=titles[view];$('.lead').textContent=view==='review'?'Här behöver kalkylarkets uppgifter förtydligas.':'Kolla samlingen innan du köper.';$('#viewHelp').textContent=view==='review'?'Dessa uppgifter räknas inte som säkert saknade. Har-listan gäller när uppgifter skiljer sig.':view==='missing'?'Saknas enligt tydliga x-markeringar i kalkylarket. Listan är ännu inte komplett; oklara varianter finns under Att granska.':'Varje post avser en version av en figur eller ett tillbehör. Antal visas när det är känt.';const query=normalize($('#search').value.trim());let results=(view==='review'?base.review:items).filter(i=>(view==='all'||view==='review'||i.status===view)&&['game','element','type'].every(k=>!$('#'+k).value||i[k]===$('#'+k).value)&&normalize([i.name,i.game,i.element,i.info,i.notes].join(' ')).includes(query));const sort=$('#sort').value;results.sort((a,b)=>(sort==='images'?Number(!!b.image)-Number(!!a.image):sort==='game'?a.game.localeCompare(b.game,'sv'):0)||a.name.localeCompare(b.name,'sv'));$('#resultCount').textContent=`${results.length} ${view==='review'?'uppgifter':'poster'}${editing?' · Redigering på':''}`;$('#grid').innerHTML=results.slice(0,limit).map(i=>`<button class="card" data-id="${esc(i.id)}" aria-label="${esc(i.name)}, ${esc(i.game)}, ${i.status==='owned'?'har':i.status==='missing'?'saknas':'att granska'}"><span class="badge ${i.status}">${i.status==='owned'?'✓ HAR':i.status==='missing'?'SAKNAS':'ATT GRANSKA'}</span><span class="card-image">${i.image?`<img src="${esc(i.image)}" alt="${esc(i.name)}" loading="lazy">`:'<span class="placeholder"><span aria-hidden="true">◇</span>Bild saknas</span>'}</span><span class="card-body"><h2>${esc(i.name)}</h2><span class="game">${esc(i.game)}</span>${i.status==='review'?`<span class="raw">${esc(i.info)}</span>`:`<span class="meta">${esc(i.element!=='Ej angivet'?i.element:i.type!=='Ej angivet'?i.type:'')}${i.quantity>1?' · '+i.quantity+' st':''}</span>`}</span></button>`).join('');$('#empty').hidden=results.length>0;$('#more').hidden=results.length<=limit;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',b.dataset.view===view)});}
function detail(id){activeId=id;const i=[...all(),...base.review].find(x=>x.id===id);if(!i)return;$('#detailContent').innerHTML=`${i.image?`<img class="detail-image" src="${esc(i.image)}" alt="${esc(i.name)}">`:''}<p class="detail-game">${esc(i.game)}</p><h2 class="detail-name">${esc(i.name)}</h2><div class="detail-grid"><p><small>Status</small>${i.status==='owned'?'Har':i.status==='missing'?'Saknas':'Behöver granskas'}</p><p><small>Antal</small>${i.quantity===null?'Inte angivet':i.quantity}</p><p><small>Element</small>${esc(i.element)}</p><p><small>Typ</small>${esc(i.type)}</p></div>${i.info?`<p>Uppgift i kalkylarket: <strong>${esc(i.info)}</strong></p>`:''}${i.status==='review'?'<p class="small">Posten kan avse flera olika varianter. Den behöver delas upp och matchas innan ägarstatus kan ändras här.</p>':editing?`<form id="editForm" class="edit-form"><label>Status<select id="statusInput"><option value="owned" ${i.status==='owned'?'selected':''}>Har</option><option value="missing" ${i.status==='missing'?'selected':''}>Saknas</option></select></label><label>Antal <input id="quantityInput" type="number" min="0" max="9999" step="1" placeholder="Okänt" value="${i.quantity===null?'':i.quantity}"></label><label>Anteckningar<textarea id="notesInput" maxlength="4000">${esc(i.notes)}</textarea></label><button class="primary" type="submit">Spara på den här enheten</button><p class="small">Detta är lokal redigering i förhandsversionen, utan inloggning eller familjesynk.</p></form>`:`${i.notes?`<p>${esc(i.notes)}</p>`:''}<p class="small">Välj Redigera högst upp för att ändra denna post.</p>`}<p class="detail-source">Källa: ${esc(i.source)}${i.imageNote?'<br>'+esc(i.imageNote):''}</p>`;if(!$('#detail').open)$('#detail').showModal();if($('#editForm')){$('#statusInput').onchange=()=>{$('#quantityInput').value=$('#statusInput').value==='missing'?'0':''};$('#editForm').onsubmit=e=>{e.preventDefault();const status=$('#statusInput').value,raw=$('#quantityInput').value,quantity=status==='missing'?0:raw===''?null:Number(raw);if(status==='owned'&&quantity!==null&&quantity<1){notify('Ange minst 1, eller lämna antal tomt.');return;}const next={...edits,[id]:{status,quantity,notes:$('#notesInput').value}};try{validate(next);localStorage.setItem(KEY,JSON.stringify(next));edits=next;}catch{notify('Kunde inte spara. Kontrollera antal och webbläsarens lagring.');return;}$('#detail').close();render();notify('Sparat i den här webbläsaren.');};}}
$('#grid').onclick=e=>{const card=e.target.closest('[data-id]');if(card)detail(card.dataset.id)};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;limit=40;render()});
for(const id of ['search','game','element','type','sort'])$('#'+id).addEventListener(id==='search'?'input':'change',()=>{limit=40;render()});
function reset(){for(const id of ['search','game','element','type'])$('#'+id).value='';limit=40;render();}$('#reset').onclick=reset;$('#emptyReset').onclick=reset;$('#more').onclick=()=>{limit+=40;render()};$('#closeDetail').onclick=()=>$('#detail').close();$('#closeBackup').onclick=()=>$('#backupDialog').close();for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
$('#editMode').onclick=()=>{editing=!editing;$('#editMode').setAttribute('aria-pressed',editing);$('#editMode').textContent=editing?'Klar':'Redigera';render();if(editing)notify('Lokal redigering på. Välj en figur för att ändra.');};
$('#backup').onclick=()=>$('#backupDialog').showModal();
$('#export').onclick=()=>{const backup={format:'skylanders-collection',version:1,createdAt:new Date().toISOString(),source:base.source,edits,catalog:base.items,collection:all().map(i=>({id:i.id,status:i.status,quantity:i.quantity,notes:i.notes})),review:base.review};const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='skylanders-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Backupen har laddats ner.');};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5e6)throw Error('För stor fil');const b=JSON.parse(await file.text());if(b.format!=='skylanders-collection'||b.version!==1)throw Error('Fel format');const next=validate(b.edits);if(!confirm('Ersätt dina lokala ändringar med denna backup?'))return;localStorage.setItem(KEY,JSON.stringify(next));edits=next;render();$('#backupDialog').close();notify('Backupen är återställd.');}catch{notify('Filen kunde inte läsas. Välj en backup från denna app.');}finally{e.target.value='';}};
render();
